DROP TABLE IF EXISTS JOINUSER;

CREATE TABLE JOINUSER(
    USERID VARCHAR(30) NOT NULL,
    USERPWD VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    USERPHONE VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(50),
    PRIMARY KEY (USERID)
);